name: GunGame
version: 1.0
author: gyuriX
main: com.thecraftcloud.gungame.GameController
depend: [TheCraftCloud-Plugin,TheCraftCloud-Client,TheCraftCloud-Core]
commands:
  jogar:
  sair:
  iniciar:
  tparena:  
  fwk:
  gg: