thecraftcloud:
   gamemanager:
      url-dev: http://localhost:8080/gamemanager/webresources
      url-prod: http://services.thecraftcloud.com:8080/gamemanager/webresources
      url: http://services-dev.thecraftcloud.com:8080/gamemanager/webresources
   